---

- name: Install template_role_extra_packages
  pkgng:
    name: "{{ template_role_extra_packages }}"
    state: present

- name: Install template_role_package
  pkgng:
    name: "{{ template_role_package }}"
    state: present

- name: Enable template_role_service
  service:
    name: "{{ template_role_service }}"
    enabled: yes

- name: "Create /etc/rc.conf.d/{{ template_role_service }}"
  template:
    src: FreeBSD.rcd.j2
    dest: "/etc/rc.conf.d/{{ template_role_service }}"
    mode: 0644
    validate: sh -n %s
  notify:
    - Restart template_role_service
