---

- name: Install template_role_extra_packages
  apt:
    name: "{{ template_role_extra_packages }}"
    state: present

- name: Install template_role_package
  apt:
    name: "{{ template_role_package }}"
    state: present

- name: Enable template_role_service
  service:
    name: "{{ template_role_service }}"
    enabled: yes

- name: "Create /etc/default/{{ template_role_service }}"
  template:
    src: Debian.default.j2
    dest: "/etc/default/{{ template_role_service }}"
    mode: 0644
    # keep the original copy in case you need the defaults in it
    backup: yes
    validate: sh -n %s
  notify:
    - Restart template_role_service
